# This is a default configuration file for IOPS.
# Edit it to suit your needs.

[nodes]
max_nodes = 16 # Max number of nodes that can be allocated (to limit computing tests)
processes_per_node = 8 # The number of processes that will be used per node. For now, this is a static parameter

[storage]
benchmark_output = /tmp/ # The path to the directory where the benchmark tool will write/read from
file_system = beegfs # Select the file system
max_volume = 34359738368 # Max volume size in bytes (to limit the size of the benchmarked file)
output_stripe_folders =  None # A list of folders with distinct striping setups. For now, these folders need to be created manually inside the benchmark_output folder using the file system utility to define the correct striping setup.

# Execution mode
# - fast: Run the benchmark without any waiting time between the tests (less accurate)
# - complete: Run the benchmark with random waiting times between the executions (more accurate)
[execution]
mode = fast # Select the mode of execution
job_manager = slurm  # Specify the job manager. If "None" is provided, the benchmark will be executed locally
slurm_constraint = bora # Some clusters use the slurm constraint parameter (-c) to define the resources. If that is your case, set the list of constraints here, otherwise put None
modules = mpi/openmpi/4.0.1 # Specify the list of modules to load using "module add <module>". If "None" is provided, no modules are loaded
workdir = /home/luan/Devel/io-ps/test/iops_run # # Specify the working directory, i.e., where the script files will be written
repetitions = 10 # The number of repetitions for each test

# Template and scripts 
[template]
slurm_template = /home/luan/Devel/io-ps/iops/templates/slurm_template.sh.j2 # If using Slurm, define the template file to generate the bash scripts. Otherwise, None.
report_template = /home/luan/Devel/io-ps/iops/templates/report_template.html # Template for the report HTML page.
ior_2_csv = /home/luan/Devel/io-ps/tools/ior_2_csv.py # Path to the ior_2_csv.py script.

