# This is a default configuration file for IOPS.
# Edit it to suit your needs.

[nodes]
max_nodes = 2 # Max number of nodes that can be allocated (to limit computing tests)
processes_per_node = 8 # The number of processes that will be used per node. For now, this is a static parameter

[storage]
benchmark_output = /beegfs/lgouveia/ # The path to the directory where the benchmark tool will write/read from
file_system = beegfs # Select the file system
max_volume = 17179869184 # Max volume size in bytes (to limit the size of the benchmarked file)
output_stripe_folders = ior_1, ior_8 # A list of folders with distinct striping setups. For now, these folders need to be created manually inside the benchmark_output folder using the file system utility to define the correct striping setup.

# Execution mode
# - fast: Run the benchmark without any waiting time between the tests (less accurate)
# - complete: Run the benchmark with random waiting times between the executions (more accurate)
[execution]
mode = fast # Select the mode of execution
job_manager = slurm  # Specify the job manager. If "None" is provided, the benchmark will be executed locally
slurm_constraint = bora # Some clusters use the slurm constraint parameter (-c) to define the resources. If that is your case, set the list of constraints here, otherwise put None
modules = mpi/openmpi/4.0.1 # Specify the list of modules to load using "module add <module>". If "None" is provided, no modules are loaded
workdir = /home/lgouveia/iops_run/ # # Specify the working directory, i.e., where the script files will be written
repetitions = 2 # The number of repetitions for each test
template = iops/templates/slurm_template.sh.j2 # If using slurm, define the template file to generate the bash scripts
ior_2_csv = tools/ior_2_csv.py # Path to ior_2_csv.py script

