# This is a default configuration file for IOPS.
# Edit it to suit your needs.

[nodes]
nodes = node[1-2], bora[22], bora[14-15], bora[17, 19-20], bora21
max_nodes = 32
max_processes_per_node = 64

[storage]
path = /path/to/storage
max_ost = 8
default_stripe_count = 4
default_stripe_size = 1048576 # In bytes
file_system = lustre  # Select the parallel file system

# Execution mode
# - fast: Run the benchmark with a reduced number of repetitions (less accurate)
# - complete: Run the benchmark with the full number of repetitions (more accurate)
[execution]
mode = fast  # Select the mode of execution

