baseURL = 'https://lgouveia.gitlabpages.inria.fr/iops/'
languageCode = 'en-us'
title = 'IOPS'
theme = 'beautifulhugo'

# Enable Git info
enableGitInfo = true

[params]
  subtitle = "A generic benchmark orchestration framework"
  logo = "images/logo.png"
  favicon = "images/logo.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false

[[menu.main]]
  name = "Home"
  url = ""
  weight = 1

[[menu.main]]
  name = "Getting Started"
  url = "getting-started/"
  weight = 2

[[menu.main]]
  name = "User Guide"
  url = "user-guide/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "about/"
  weight = 4

[[menu.main]]
  name = "Blog"
  url = "blog/"
  weight = 5

[[menu.main]]
  name = "Reports"
  url = "reports/"
  weight = 6

[[menu.main]]
  name = "Search"
  url = "search/"
  weight = 7

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    style = "monokai"
