# This is a default configuration file for IOPS.
# Edit it to suit your needs.

[nodes]
max_nodes = 32 # Max number of nodes that can be allocated (to limit computing tests)
processes_per_node = 8 # The number of processes that will be used per node. For now, this is a static parameter

[storage]
filesystem_dir = /tmp/ # The path to the directory where the benchmark tool will write/read from
max_volume = 34359738368 # Max volume size in bytes (to limit the size of the benchmarked file). Warning: the volume needs to be power of 2.
stripe_folders = None # A list of folders with distinct striping setups.
	# If 'None' is provided, the striping test will not be executed.
	# For now, these folders need to be created manually inside the benchmark_output folder using the file system
	# utility to define the correct striping setup. These folders need to be defined using a sequential number
	# (the larger the number, the more OSTs); a good approach is to use the number of OSTs as this number.
	# Otherwise, you may encounter problems in the striping graph.
	

# Execution mode
# - fast: Run the benchmark without any waiting time between the tests (less accurate)
# - complete: Run the benchmark with random waiting times between the executions (more accurate)
[execution]
mode = fast # Select the mode of execution
job_manager =  local # Specify the job manager. If "local" is provided, the benchmark will be executed locally
benchmark_tool = ior  # Specify the benchmark tool to use. For now, only IOR is supported.
modules = None # Specify the list of modules to load using "module add <module>". If "None" is provided, no modules are loaded
workdir = /tmp/ # # Specify the working directory, i.e., where the script files will be written
repetitions = 5 # The number of repetitions for each test

# Template and scripts 
[template]
slurm_template =  None # If using Slurm, define the template file to generate the bash scripts. Otherwise, None.
report_template = /home/luan/Devel/io-ps/iops/templates/report_template.html # Template for the report HTML page.
ior_2_csv = /home/luan/Devel/io-ps/tools/ior_2_csv.py # Path to the ior_2_csv.py script.

# Slurm parameters (only used if slurm is selected as the job manager)
[slurm]
slurm_constraint =  None # Some clusters use the slurm constraint parameter (-c) to define the resources. If that is your case, set the list of constraints here, otherwise put None
slurm_partition = None # The partition to be used. If None, no partition is defined
slurm_time = None # The maximum time for the job. If None, no time is defined

