#This is a default configuration file for IOPS. You can edit it to suit your needs.
#Nodes configuration
[nodes]
nodes = bora[1-32]
max_cpu_per_node = 32
max_processes = 64

#Storage configuration
[storage]
path = /path/to/storage

