from iops.core.config import IOPSConfig
from iops.util.generator import Generator
from iops.util.submitter import Slurm
from iops.util.submitter import Local
from iops.util.tags import TestType


from typing import List, Optional, Any
from rich.console import Console
import time
from pathlib import Path


console = Console()       


class TestIOR:
    """
    Represents a single IOR test, containing the parameters required to execute the test.
    """
    _id_counter = 0

    def __init__(self, volume: int, folder_index: int, computing: int, config: 'IOPSConfig', test_path: Path):
        """
        Initializes a new instance of a test.
        
        :param volume: The volume parameter for the test.
        :param folder_index: The folder parameter for the test.
        :param computing: The computing parameter for the test.
        :param config: The configuration object for I/O operations.
        """
        type(self)._id_counter += 1
        self.test_id = self._id_counter
        self.volume = volume
        self.folder_index = folder_index
        self.computing = computing
        self.config = config

        self.test_path = test_path
        self.batch_file = Path(self.test_path, f"batch_{self.test_id}.sh")
    
    def __get_ior_command(self, delete_generate_file: bool) -> str:
        """
        Generate the IOR command based on the parameters defined in TestIOR.
        """
        
        ior_command : str = "ior "

        block_size : int = self.volume / (self.config.processes_per_node * self.config.max_nodes)
       
        # Add parameters to the command

        ior_command += f" -w" # only write operation for now
        ior_command += f" -t 1m"  
        ior_command += f" -b {block_size}b"  

        # delete the generate file at the end
        if delete_generate_file:
            ior_command += f" -k"    
        # Path where the output will be written, change name_file.ior
        ior_command += f" -o {self.config.filesystem_dir}/name_file.ior"  
        
        return ior_command

    def generate_batch_file(self) -> dict:
        """
        Generate a batch file capable of executing the IOR command generated by the previous method.
        """
        parameters = {
            "job_name": f"iops_{self.test_id}",
            "partition": f"{self.config.slurm_partition}",
            "ntasks": self.config.max_nodes,
            "nodes": self.computing,                
            "ntasks_per_node": self.config.processes_per_node,
            "time": "04:00:00",
            "chdir": self.test_path,
            "constraint": self.config.slurm_constraint,
            "modules": self.config.modules,
            "benchmark_cmd": self.__get_ior_command(True)
        }
        # return self.__generate_batch_file(self.batch_file, parameters)
        return parameters
        # to test 
        # Generator.slurm_script(self.config.slurm_template, self.batch_file, parameters)
        # Generator.local_script(self.config.local_template, self.batch_file, parameters)
        # return 
            

    def __repr__(self):
        return f"<Test {self.test_id} Batch: {self.batch_file} volume={self.volume}, folder_index={self.config.stripe_folders[self.folder_index]}, computing={self.computing}>"

    @classmethod
    def from_existing(cls, existing_test: 'TestIOR'):
        """
        Creates a new TestIOR object based on an existing one.
        
        :param existing_test: An instance of TestIOR from which to create a new instance.
        """
        # Create a new instance using the attributes of the existing test
        return cls(existing_test.volume, existing_test.folder_index, existing_test.computing, existing_test.config, existing_test.test_path)

class Round:
    """
    Represents a round of tests, generating and managing Test instances
    based on the configured test type.
    """
    _id_counter = 0

    def __init__(self,  volume: int, folder_index: int,  computing: int, config: IOPSConfig, test_type: TestType):
        type(self)._id_counter += 1
        self.round_id = self._id_counter
        

        self.test_type = test_type
        self.config = config
        
        self.round_path = self.config.workdir / self.test_type.name.lower() / f"round_{self.round_id}"

        # create the directory
        self.round_path.mkdir(parents=True, exist_ok=True)


        self.current_test = TestIOR(volume=volume,
                                 folder_index=folder_index, 
                                 computing=computing,
                                 config=config, test_path=self.round_path)
    
    def get_current_test(self) -> TestIOR:
        return self.current_test

    def next(self) -> None: 
        """
        Generates the next Test instance based on the test type and current state
        """
        # copy the current test and update it
        next_test = TestIOR.from_existing(self.current_test)
        
        if self.test_type == TestType.COMPUTING:              
            if  next_test.computing < self.config.max_nodes:
                next_test.computing += 1
            else:
                next_test =  None # no more tests to run
                
        if self.test_type == TestType.FILESIZE:            
            if next_test.volume < self.config.max_volume:
                next_test.volume += 1073741824                                
            else:
                next_test = None # no more tests to run        

        if self.test_type == TestType.STRIPING:            
            if next_test.folder_index < len(self.config.stripe_folders) - 1:
                next_test.folder_index += 1
            else:
                next_test = None
        
        self.current_test = next_test

    def __repr__(self) -> str:
        return f"Round {self.round_id} test_type={self.test_type}, current_test={self.current_test}"



class Runner:
    """
    The Runner class orchestrates the execution of tests defined within a Round.
    It provides static methods to execute individual tests based on predefined parameters and manages the overall test execution flow,
    ensuring all tests within a round are run sequentially until completion, without requiring an instance of the class.
    """

    @staticmethod
    def _run(test: TestIOR) -> None:
        """
        Executes a given test by building the appropriate batch file and submitting it for execution.
        
        Parameters:
        - test (Any): A set of pre-defined parameters that describe the test to be executed.
        """
        parameters = test.generate_batch_file()
        if (test.config.job_manager == "slurm"):
            Generator.slurm_script(test.config.slurm_template, test.batch_file, parameters)
            console.print(f"[bold green]Run Test:[/bold green] {test}")
            Slurm.submit_slurm(test.batch_file)
        else:
            Generator.local_script(test.config.local_template, test.batch_file, parameters)
            Local.submit_local(test.batch_file)
            console.print(f"[bold green]Run Test:[/bold green] {test}")
            

    @staticmethod
    def run(round: Round) -> Round:
        """
        Executes the tests within a given Round, sequentially calling the next test until all tests are completed.
     
        Parameters:
        - round (Round): The Round object containing the tests to be executed.

        Returns:
        - Round: The same Round object, after all tests have been executed.
        """
        start_time = time.time()

        try:
            while True:

                test = round.get_current_test()                
                if test:
                    Runner._run(test)  # Execute the test using the static method.
                else:
                    break  # Exit the loop if there are no more tests.

                round.next()  # Move to the next test in the round.

                

        except KeyboardInterrupt:
            # Handle user interruption.
            # Assuming console is a logging or output object you've defined elsewhere
            console.print("[bold red]Aborting test due to user interruption.")
            console.print("[bold yellow]Warning:[/bold yellow] You may have an ongoing job in the job manager.")
            error = True

        except Exception as e:
            # Handle general exceptions.
            console.print(f"[bold red]Error:[/bold red] {str(e)}")
            error = True

        end_time = time.time()
        execution_time = end_time - start_time  
        formatted_time = Runner.__format_time(execution_time) 
        console.print(f"[bold green]Round Execution Time:[/bold green] {formatted_time}")

        return round

    @staticmethod
    def __format_time(seconds: float) -> str:
        hours, remainder = divmod(int(seconds), 3600)
        minutes, seconds = divmod(remainder, 60)
        return f"{hours} hours, {minutes} minutes, and {seconds} seconds"
        


      