from iops.core.config import IOPSConfig
from iops.util import generator
from iops.util.tags import TestType


from typing import List, Optional, Any
from rich.console import Console
import time
from pathlib import Path

console = Console()       


class TestIOR:
    """
    Represents a single IOR test, containing the parameters required to execute the test.
    """

    def __init__(self, volume: int, folder_index: int, computing : int, config: IOPSConfig):
        """
        Initializes a new instance of a test.
        
        :param volume: The volume parameter for the test.
        :param folder: The folder parameter for the test.
        :param computing: The computing parameter for the test.
        """
        self.volume = volume
        self.folder_index = folder_index
        self.computing = computing

        self.config = config
    
    def __get_ior_command(self, delete_generate_file: bool) -> str:
        """
        Generate the IOR command based on the parameters defined in TestIOR.
        """
        
        ior_command : str = "ior "

        block_size : int = self.volume / (self.config.processes_per_node * self.config.max_nodes)
        # block_size = block_size * 1024
        volume_mb : int = self.volume / 1024
        
        # Add parameters to the command

        ior_command += f" -w " # only write operation for now
        ior_command += f" -t {volume_mb}m"  # Volume size mb
        ior_command += f" -b {block_size}b"  # Transfer size in MB
        ior_command += f" -k {delete_generate_file}"  # Do not delete the generate file at the end
        ior_command += f" -o {self.config.filesystem_dir}/name_file.ior"  # Path where the output will be written, change name_file.ior
        
        return ior_command

    def generate_batch_file(self, file_path: Path) -> Path:
        """
        Generate a batch file capable of executing the IOR command generated by the previous method.
        """
        parameters = {
            "job_name": f"iops_striping_{i+1}",
            #"partition": "The partition to submit the job to",
            "ntasks":self.config.max_nodes,
            "nodes": self.computing,                
            "ntasks_per_node": self.config.processes_per_node,
            "time": "04:00:00",
            "chdir": file_path,
            "constraint": self.config.slurm_constraint,
            "modules": self.config.modules,
            # "ior_output_path": self.config.workdir,
            "ior_parameter": self.__get_ior_command()

        }
        
        
        
        generator.slurm_script(self.config.slurm_template, script_path, parameters)
            

    def __repr__(self):
        return f"<Test volume={self.volume}, folder_index={self.config.stripe_folders[self.folder_index]}, computing={self.computing}>"

class Round:
    """
    Represents a round of tests, generating and managing Test instances
    based on the configured test type.
    """

    def __init__(self,  volume: int, folder_index: int,  computing: int, config: IOPSConfig, test_type: TestType):
        self.round_id = None # <--- Add a unique identifier for the round

        self.test_type = test_type
        self.config = config

        self.current_test = TestIOR(volume=volume,
                                 folder_index=folder_index, 
                                 computing=computing,
                                 config=config)
        
        self.__generate_directory_structure()


    def __generate_directory_structure(self) -> None:
        '''
        this method generates a directory structure that represents a round. The folder is created in the workdir directory and has the following structure:

        workdir/<round_id>_<test_type>/
            - exec_01/
            - exec_02/
            - exec_03/
            ...
            - exec_<max_exec>/
        '''
        pass

    def get_current_test(self) -> TestIOR:
        return self.current_test

    def next(self) -> None: 
        """
        Generates the next Test instance based on the test type and current state
        """
        # copy the current test and update it
        next_test : TestIOR = self.current_test
        
        if self.test_type == TestType.COMPUTING:              
            if  next_test.computing < self.config.max_nodes:
                next_test.computing += 1
            else:
                next_test =  None # no more tests to run
                
        if self.test_type == TestType.FILESIZE:            
            if next_test.volume < self.config.max_volume:
                next_test.volume += 1073741824                                
            else:
                next_test = None # no more tests to run        

        if self.test_type == TestType.STRIPING:            
            if next_test.folder_index < len(self.config.stripe_folders) - 1:
                next_test.folder_index += 1
            else:
                next_test = None
        
        self.current_test = next_test
        

    def __repr__(self) -> str:
        return f"Round test_type={self.test_type}, current_test={self.current_test}"



class Runner:
    """
    The Runner class orchestrates the execution of tests defined within a Round.
    It provides static methods to execute individual tests based on predefined parameters and manages the overall test execution flow,
    ensuring all tests within a round are run sequentially until completion, without requiring an instance of the class.
    """

    @staticmethod
    def _run(test: dict) -> None:
        """
        Executes a given test by building the appropriate batch file and submitting it for execution.
        
        Parameters:
        - test (Any): A set of pre-defined parameters that describe the test to be executed.
        """
        console.print(f"[bold green]Run Test:[/bold green] {test}")

    @staticmethod
    def run(round: Round) -> Round:
        """
        Executes the tests within a given Round, sequentially calling the next test until all tests are completed.
     
        Parameters:
        - round (Round): The Round object containing the tests to be executed.

        Returns:
        - Round: The same Round object, after all tests have been executed.
        """
        start_time = time.time()

        try:
            while True:

                test = round.get_current_test()                

                if test:
                    Runner._run(test)  # Execute the test using the static method.
                else:
                    break  # Exit the loop if there are no more tests.

                round.next()  # Move to the next test in the round.

                

        except KeyboardInterrupt:
            # Handle user interruption.
            # Assuming console is a logging or output object you've defined elsewhere
            console.print("[bold red]Aborting test due to user interruption.")
            console.print("[bold yellow]Warning:[/bold yellow] You may have an ongoing job in the job manager.")
            error = True

        except Exception as e:
            # Handle general exceptions.
            console.print(f"[bold red]Error:[/bold red] {str(e)}")
            error = True

        end_time = time.time()
        execution_time = end_time - start_time  
        formatted_time = Runner.__format_time(execution_time) 
        console.print(f"[bold green]Round Execution Time:[/bold green] {formatted_time}")

        return round

    @staticmethod
    def __format_time(seconds: float) -> str:
        hours, remainder = divmod(int(seconds), 3600)
        minutes, seconds = divmod(remainder, 60)
        return f"{hours} hours, {minutes} minutes, and {seconds} seconds"
        


      