from iops.core.config import IOPSConfig
from iops.util.generator import Generator, Graphs
from iops.util.submitter import Submitter
from iops.util.tags import TestType, jobManager, ExecutionMode



import pandas as pd
from pathlib import Path
import subprocess
import random


from typing import List
from rich.console import Console
from rich.progress import Progress, BarColumn, TextColumn, TaskProgressColumn
from rich.panel import Panel
import time
from pathlib import Path


console = Console()       

# Define the style of the progress bar
progress_columns = [
    TextColumn("[bold green]{task.fields[round_id]}[/]", justify="left"),
    BarColumn(bar_width=20, complete_style="green3", finished_style="bold green"),
    TextColumn("[progress.percentage]"),
    TaskProgressColumn(),
    TextColumn("({task.completed}/{task.total} tests)")
]

class TestIOR:
    """
    Represents a single IOR test, containing the parameters required to execute the test.
    """
    _id_counter = 0

    def __init__(self, volume: int, folder_index: int, computing: int, config: 'IOPSConfig', round_path: Path):
        """
        Initializes a new instance of a test.
        
        :param volume: The volume parameter for the test.
        :param folder_index: The folder parameter for the test.
        :param computing: The computing parameter for the test.
        :param config: The configuration object for I/O operations.
        """
        type(self)._id_counter += 1
        self.test_id = self._id_counter
        self.volume = volume
        self.folder_index = folder_index
        self.computing = computing
        self.config = config

        self.round_path = round_path
        self.batch_path = round_path / f"test_{self.test_id}"      
        # self.summary_path = round_path / f"summary_{self.test_id}"
        self.summary_file = self.batch_path / f"summary_test_{self.test_id}_$(date +%Y%m%d%H%M%S)_$RANDOM.out"
        self.batch_file = self.batch_path / f"batch_{self.test_id}.sh"
    
    def __get_ior_command(self, delete_generate_file: bool) -> str:
        """
        Generate the IOR command based on the parameters defined in TestIOR.
        """
        
        ior_command : str = "ior"

        block_size : int = self.volume / (self.config.processes_per_node * self.computing)
       
        # Add parameters to the command

        ior_command += f" -w" # only write operation for now
        ior_command += f" -t 1m"  
        ior_command += f" -b {block_size}b"  

        # delete the generate file at the end
        if not delete_generate_file:
            ior_command += f" -k" 
        ior_command += f" -O summaryFile={self.summary_file}" # Path where the output will be written 
        ior_command += f" -O summaryFormat=default"
        # Path where the output will be written 
        ior_command += f" -o {self.config.get_stripe_folder(self.folder_index)}/test{self.test_id}.ior"
        
        return ior_command

    def build_files(self) -> None:
        """
        Generate a batch file capable of executing the IOR command generated by the previous method.
        """
        # First create the folder for the test
        self.batch_path.mkdir(parents=True, exist_ok=True)

        parameters = {}
        if self.config.modules is not None:
            parameters["modules"] = self.config.modules
    
        if self.config.slurm_constraint is not None:
            parameters["constraint"] = self.config.slurm_constraint
        
        if self.config.slurm_partition is not None:
            parameters["partition"] = self.config.slurm_partition
        
        if self.config.slurm_time is not None:
            parameters["time"] = self.config.slurm_time
        else:
            parameters["time"] = "04:00:00"
        
        parameters["job_name"] = f"iops_{self.test_id}"
        parameters["chdir"] = self.batch_file.parent
        parameters["ntasks"] = self.computing * self.config.processes_per_node
        parameters["nodes"] = self.computing
        parameters["ntasks_per_node"] = self.config.processes_per_node
        parameters["benchmark_cmd"] = self.__get_ior_command(True)
        
        # Generate the execution script
        Generator.from_template(template_path=self.__template, output_path=self.batch_file, info=parameters)
        
    @property
    def __template(self):
        if self.config.job_manager == jobManager.SLURM:
            return self.config.slurm_template   
        elif self.config.job_manager == jobManager.LOCAL:
            return self.config.local_template
        else:
            return None     

    def __bytes_to_mb(self, bytes: int) -> float:
        """
        Converts bytes to megabytes.
        
        :param bytes: The number of bytes to convert.
        """
        return bytes / 1024.0 / 1024.0
    
    def __repr__(self):
        return f"\t{self.test_id:04}: \[volume={self.__bytes_to_mb(self.volume)}MB, folder_index={self.config.stripe_folders[self.folder_index]}, computing={self.computing}]"


    @classmethod
    def from_existing(cls, existing_test: 'TestIOR'):
        """
        Creates a new TestIOR object based on an existing one.
        
        :param existing_test: An instance of TestIOR from which to create a new instance.
        """
        # Create a new instance using the attributes of the existing test
        return cls(existing_test.volume, existing_test.folder_index, existing_test.computing, existing_test.config, existing_test.round_path)

class Round:
    """
    Represents a round of tests, generating and managing Test instances
    based on the configured test type.
    """
    _id_counter = 0

    def __init__(self,  volume: int, folder_index: int,  computing: int, config: IOPSConfig, test_type: TestType):
        type(self)._id_counter += 1
        self.round_id = self._id_counter
        
        self.test_type = test_type
        self.config = config
        
        self.round_path = self.config.workdir / self.test_type.name.lower() / f"round_{self.round_id}"

        # create the directory
        self.round_path.mkdir(parents=True, exist_ok=True)

        # create the directory for the summary files
        # self.summary_path = self.round_path / "summary"
        # self.summary_path.mkdir(parents=True, exist_ok=True)

        # create a list of tests to store all the tests
        self.list_test : List[TestIOR] = []
                
        self.df = None
        self.csv_file = self.round_path / f"{self.test_type.name}_{self.round_id}.csv"
        self.graph_file = self.round_path / f"{self.test_type.name}_{self.round_id}.svg"

        self.all_tests : List[TestIOR] = []
        self.__current_pos = 0
        self.__repetition = 0
        
        # generate all tests
        self.__generate_all_tests(volume=volume, folder_index=folder_index, computing=computing)

        # computing the number of tests
        self.number_of_tests = len(self.all_tests) * self.config.repetitions
        
       
    def __load_results(self):
        '''
        load the results of the tests, for instance by generating a csv file and loading it into a pandas dataframe
        it can also generate a graph based on the results
        '''
        args = [self.config.ior_2_csv, self.round_path, self.csv_file]

        try:
            result = subprocess.run(args, check=True)
            if result.returncode != 0:
                raise Exception(f"Error: Script {self.config.ior_2_csv} finished with a non-zero return code: {result.returncode}")
            # load the csv file into a pandas dataframe
            self.df = pd.read_csv(self.csv_file)
            # generate the graph
            Graphs.generate(self.df, self.graph_file, self.test_type)

        except subprocess.CalledProcessError as e:
            raise Exception(f"Error: Script execution failed: {e}")
        
        except Exception as e:
            raise Exception(f"Error: {e}")

    def __generate_all_tests(self, volume: int, folder_index: int, computing: int):
        next_test =  TestIOR(volume=volume,
                                 folder_index=folder_index, 
                                 computing=computing,
                                 config=self.config, 
                                 round_path=self.round_path)  
        while next_test is not None:

            # Before the append, we need to create the script for the test
            next_test.build_files()
            # save the test in the list of all tests and create a new test based on the current one
            self.all_tests.append(next_test)
            next_test = TestIOR.from_existing(next_test)
            
            if self.test_type == TestType.COMPUTING:              
                if  next_test.computing < self.config.max_nodes:
                    next_test.computing += 1
                else:
                    next_test =  None # no more tests to run

            if self.test_type == TestType.FILESIZE:            
                if next_test.volume < self.config.max_volume:
                    next_test.volume += 536870912                                
                else:
                    next_test = None # no more tests to run        

            if self.test_type == TestType.STRIPING:            
                if next_test.folder_index < len(self.config.stripe_folders) - 1:
                    next_test.folder_index += 1
                else:
                    next_test = None
        # randomize the list of tests
        random.shuffle(self.all_tests)
            

    def next(self) -> TestIOR | None:
        """
        Updates the next Test instance to be executed in the round.
        """
                
        if self.__current_pos == 0 and self.__repetition < self.config.repetitions:
            console.print(f"Repetition {self.__repetition + 1}/{self.config.repetitions}", style="bold white on red")

        next_test = None
        if self.__repetition < self.config.repetitions:
            next_test = self.all_tests[self.__current_pos]
            self.__current_pos += 1 
            if self.__current_pos >= len(self.all_tests):                                                
                self.__current_pos = 0
                self.__repetition += 1
                random.shuffle(self.all_tests)
        else:            
            self.__load_results()
        
        return next_test
            
    def __repr__(self) -> str:
        return f"Round {self.round_id} \[{self.test_type.name}]"



class Runner:
    """
    The Runner class orchestrates the execution of tests defined within a Round.
    It provides static methods to execute individual tests based on predefined parameters and manages the overall test execution flow,
    ensuring all tests within a round are run sequentially until completion, without requiring an instance of the class.
    """

    @staticmethod
    def _run(test: TestIOR) -> None:
        """
        Executes a given test by building the appropriate batch file and submitting it for execution.
        
        Parameters:
        - test (Any): A set of pre-defined parameters that describe the test to be executed.
        """        
        console.print(f"{test}")
        # running the test
        if test.config.mode != ExecutionMode.DEBUG:
            result = Submitter.submit(test.batch_file, test.config.job_manager)                
            if result.returncode != 0:                
                console.print(f"\tTest: {test.test_id} Failed: {result.stderr.decode('utf-8')}", style="bold red")

            

    @staticmethod
    def run(round: Round) -> Round:
        """
        Executes the tests within a given Round, sequentially calling the next test until all tests are completed.
     
        Parameters:
        - round (Round): The Round object containing the tests to be executed.

        Returns:
        - Round: The same Round object, after all tests have been executed.
        """
        start_time = time.time()

        try:            
            console.print(Panel(f"{round}", style="bold green", expand=True))

            # Create the Progress instance with the defined columns
            with Progress(*progress_columns, console=console) as progress:
                # Start a task with specific metadata for the round and total number of tests
                round_task = progress.add_task("[green]Round", round_id=f"Round {round.round_id}",
                                            total=round.number_of_tests)

                while True:

                    test = round.next()  # Move to the next test in the round.            
                    if test:
                        Runner._run(test)  # Execute the test using the static method.
                    else:
                        break  # Exit the loop if there are no more tests.
                        
                    progress.update(round_task, advance=1)  # Update the progress bar.
                    
                

                
                

        except KeyboardInterrupt:
            # Handle user interruption.
            # Assuming console is a logging or output object you've defined elsewhere
            console.print("[bold red]Aborting test due to user interruption.")
            console.print("[bold yellow]Warning:[/bold yellow] You may have an ongoing job in the job manager.")

        except Exception as e:
            # Handle general exceptions.
            console.print(f"[bold red]Error:[/bold red] {str(e)}")

        # console.print(f"List of tests: {round.list_test}")

        end_time = time.time()
        execution_time = end_time - start_time  
        formatted_time = Runner.__format_time(execution_time) 
        console.print(f"[bold green]Round Execution Time:[/bold green] {formatted_time}")

        return round

    @staticmethod
    def __format_time(seconds: float) -> str:
        hours, remainder = divmod(int(seconds), 3600)
        minutes, seconds = divmod(remainder, 60)
        return f"{hours} hours, {minutes} minutes, and {seconds} seconds"
        


      