
from iops.core.config import IOPSConfig
from iops.util.generator import Generator
from iops.util.tags import jobManager_Tag, Parameter, Pattern, FileMode, ExecutionMode, TestFlags, Operation

from pathlib import Path
from abc import ABC, abstractmethod
import copy

from datetime import datetime
from abc import ABC, abstractmethod
import subprocess
import pandas as pd
from random import randint

class Test(ABC):
    """
    Represents a test to be executed in the IOPS benchmark. 
    This class serves as a base class for creating test scenarios with various configurations and behaviors. 
    It is designed to be subclassed, with subclasses needing to process specific test parameters and implement the method to build necessary files.
    """
    _id_counter = 0

    def __init__(self, config: 'IOPSConfig', round_path: Path, test_parameters: dict):
        """
        Initializes a new test instance, setting up essential file paths and storing configuration details.
        
        :param config: Configuration object containing settings for I/O operations.
        :param round_path: Base path where test files will be located.
        :param test_parameters: Dictionary of parameters that define test specifics. These parameters need to be handled appropriately by any class that inherits from this class.
        """
        type(self)._id_counter += 1
        self.test_id = self._id_counter        
        
        self.config = config
        self.round_path = round_path
        self.test_parameters = copy.deepcopy(test_parameters)

        self.batch_path = round_path / f"test_{self.test_id}"

        self.batch_file = self.batch_path / f"batch_{self.test_id}.sh"
        self.summary_file = self.batch_path / f"summary_test_{self.test_id}_$(date +%Y%m%d%H%M%S)_$RANDOM.out"
        self.csv_file = self.batch_path / f"result.csv"
        

        self.number_of_executions = 0

        self.was_executed = False
        self.df = None
    
    @property
    def bw(self):
        if self.df is not None:
            return self.df["bw"].mean()
        else:
            return None
    
    @property
    def volume(self) -> int:
        """
        The volume of data involved in the test, in MB.
        """
        return self.test_parameters[Parameter.FILESIZE]
    
    @property
    def output_file(self) -> Path:
        """
        Full path to the output file written by the benchmark.
        """
        return Path(self.test_parameters[Parameter.STRIPING], f"test{self.test_id}.ior")
    
    @property
    def computing(self) -> int:
        """
        The number of computing nodes or processes dedicated to this test.
        """
        return self.test_parameters[Parameter.COMPUTING]

    @property
    def keep_files(self) -> bool:
        """
        Whether to keep the files generated by the test after execution.
        """
        return self.test_parameters[TestFlags.KEEP_FILES]


    @classmethod
    def create_test(cls, pattern: Pattern, file_mode: FileMode, config: 'IOPSConfig', round_path: Path, test_parameters: dict, operation: Operation) -> 'Test':
        """
        Factory method to create test instances based on the test pattern and operation.
        
        :param pattern: The I/O pattern for the test.
        :param operation: The type of operation to be performed.
        :param config: Configuration object for the test.
        :param round_path: Path where test files will be located.
        :param test_parameters: Dictionary of specific test parameters.
        :return: An instance of a subclass of Test.
        """
        if operation == Operation.WRITE:
            if pattern == Pattern.SEQUENTIAL and file_mode == FileMode.SHARED:
                return WriteIORSeq(config, round_path, test_parameters)
            elif pattern == Pattern.RANDOM and file_mode == FileMode.SHARED:
                return WriteIORRandom(config, round_path, test_parameters)      
            else:
                raise ValueError(f"Unsupported test pattern and file mode combination: {pattern}:{file_mode}")
        elif operation == Operation.READ:
            if pattern == Pattern.SEQUENTIAL and file_mode == FileMode.SHARED:
                return ReadIORSeq(config, round_path, test_parameters)
            elif pattern == Pattern.RANDOM and file_mode == FileMode.SHARED:
                return ReadIORRandom(config, round_path, test_parameters)
            else:
                raise ValueError(f"Unsupported test pattern and file mode combination: {pattern}:{file_mode}")
        else:
            raise ValueError(f"Unsupported I/O operation: {operation}")

    @abstractmethod
    def build_files(self) -> None:
        """
        Abstract method that must be implemented by subclasses to generate the files needed to execute the test.
        Subclasses should provide their own implementation to handle file generation based on the test configuration and parameters.
        """
        pass
    
    @abstractmethod
    def get_command(self) -> str:
        """
        Abstract method that must be implemented by subclasses to generate the command to execute the test.
        Subclasses should provide their own implementation to handle command generation based on the test configuration and parameters.
        """
        pass
    
    def load_results(self):
        """
        Load the results of the tests
        """
        args = [self.config.ior_2_csv, self.batch_path, self.csv_file]
        try:
            if self.config.mode is not ExecutionMode.DEBUG:
                # if not in debug mode, run the command
                result = subprocess.run(args, capture_output=True)
                if result.returncode != 0:
                    raise ValueError(f"Error converting IOR output to CSV: {result.stderr}")
                self.was_executed = True
        
        except subprocess.CalledProcessError as e:
            raise Exception(f"Error: Script execution failed: {e}")
        
        except Exception as e:
            raise Exception(f"Error: {e}")
        
        self.number_of_executions += 1
        self.df = pd.read_csv(self.csv_file)
        

    @classmethod
    def from_existing(cls, existing_test: 'Test'):
        """
        Creates a new instance based on an existing test instance. This method dynamically determines the class of the existing test and creates a new instance of that class.

        :param existing_test: An instance of a subclass of Test from which to create a new instance.
        """
        if isinstance(existing_test, Test):
            # Dynamically get the class of the existing test and use it to create a new instance.
            existing_class = type(existing_test)
            return  existing_class(config=existing_test.config, 
                                  round_path=existing_test.round_path, 
                                  test_parameters=existing_test.test_parameters)
            
        

        else:
            raise TypeError(f"Cannot create a new instance from the given test object. It must be a non-abstract subclass of Test.")

    def __repr__(self):
        msg_str = f"\t{self.test_id:04}: "
        for key, value in self.test_parameters.items():            
            msg_str += f"\[{key.name}={value}] "
        
        return msg_str

    def __eq__(self, other: 'Test') -> bool:
        return abs(self.bw - other.bw) <= self.config.static_bw_alpha    

    def __le__(self, other: 'Test') -> bool:
        return  self.bw < other.bw or self.__eq__(other)     
    
    def __ge__(self, other: 'Test') -> bool:
        return  self.bw > other.bw or self.__eq__(other)
    
    def __lt__(self, other: 'Test') -> bool:
        return  self.bw < other.bw and not self.__eq__(other)
    
    def __gt__(self, other: 'Test') -> bool:
        return  self.bw > other.bw and not self.__eq__(other)

class TestIOR(Test):
    """
    Base class for IOR tests. It provides common functionality for IOR tests, such as generating the IOR command and building the batch file.
    """

    def __init__(self, config: 'IOPSConfig', round_path: Path, test_parameters: dict):
       super().__init__(config, round_path, test_parameters)
       
    
    def build_files(self) -> None:
        """
        Generate a batch file capable of executing the IOR command generated by the previous method.
        """
        # First create the folder for the test
        self.batch_path.mkdir(parents=True, exist_ok=True)

        parameters = {}
        if self.config.modules is not None:
            parameters["modules"] = self.config.modules
    
        if self.config.slurm_constraint is not None:
            parameters["constraint"] = self.config.slurm_constraint
        
        if self.config.slurm_partition is not None:
            parameters["partition"] = self.config.slurm_partition
        
        parameters["time"] = self.config.slurm_time        
        
        parameters["job_name"] = f"iops_{self.test_id}"
        parameters["chdir"] = self.batch_file.parent
        parameters["ntasks"] = self.computing * self.config.processes_per_node
        parameters["nodes"] = self.computing
        parameters["ntasks_per_node"] = self.config.processes_per_node
        
        # number of cores per task
        parameters['cores_per_task'] = self.config.cores_per_node // self.config.processes_per_node

        parameters["benchmark_cmd"] = self.get_command()
        
        # Generate the execution script
        Generator.from_template(template_path=self.config.bash_template, output_path=self.batch_file, info=parameters)

class WriteIORSeq(TestIOR):
    """
    I/O pattern: sequential write in a single shared file.
    Parameters:
    - volume: The amount of data (in MB) involved in the test.
    - output_file: The path where the output will be written.
    - computing: The number of computing nodes involved in the I/O operation.
    """

    def get_command(self) -> str:
        """
        Generate the IOR command based on the parameters defined in TestIOR.
        """

        ior_command : str = "ior"

        block_size : int = self.volume / (self.config.processes_per_node * self.computing)
       
        # Add parameters to the command

        ior_command += f" -w" # only write operation for now
        ior_command += f" -t 1m"  
        ior_command += f" -b {int(block_size)}m"  

        
        if self.keep_files:
            ior_command += f" -k" # keep the file
        ior_command += f" -O summaryFile={self.summary_file}" # Path where the output will be written 
        ior_command += f" -O summaryFormat=default"
        # Path where the output will be written 
        ior_command += f" -o {self.output_file}"
        
        return ior_command

class WriteIORRandom(TestIOR):
    """
    I/O pattern: random write in a single shared file.
    Parameters:
    - volume: The amount of data (in MB) involved in the test.
    - output_file: The path where the output will be written.
    - computing: The number of computing nodes involved in the I/O operation.
    """

    def get_command(self) -> str:
        """
        Generate the IOR command based on the parameters defined in TestIOR.
        """        
        ior_command : str = "ior"

        block_size : int = self.volume / (self.config.processes_per_node * self.computing)
       
        # Add parameters to the command

        ior_command += f" -w" # only write operation for now
        ior_command += f" -t 1m"  
        ior_command += f" -b {int(block_size)}m"  
        

        # delete the generate file at the end
        if self.keep_files:
            ior_command += f" -k"
        ior_command += f" -z" # random access
        ior_command += f" --random-offset-seed={randint(1, 1000)}"
        ior_command += f" -O summaryFile={self.summary_file}" # Path where the output will be written 
        ior_command += f" -O summaryFormat=default"
        # Path where the output will be written 
        ior_command += f" -o {self.output_file}"
        
        return ior_command

class ReadIORSeq(TestIOR):
    '''
    I/O pattern: sequential read in a single shared file.
    '''
    def __init__(self, config: 'IOPSConfig', round_path: Path, test_parameters: dict):
        super().__init__(config, round_path, test_parameters)
        self.input_file = None

    def set_input_file(self, input_file: Path) -> None:
        """
        Set the input file for the read operation.
        
        :param input_file: The path to the input file to be read.
        """
        self.input_file = input_file
        if not self.config.mode == ExecutionMode.DEBUG and not self.input_file.exists():
            raise ValueError(f"Input file {self.input_file} does not exist. Please set a valid input file.")

    def get_command(self) -> str:
        """
        Generate the IOR command based on the parameters defined in TestIOR.
        """        
        if self.input_file is None:
            raise ValueError("Input file not set. Please set the input file before generating the command.")
        
        ior_command : str = "ior"

        block_size : int = self.volume / (self.config.processes_per_node * self.computing)
       
        # Add parameters to the command

        ior_command += f" -r" 
        ior_command += f" -t 1m"  
        ior_command += f" -b {int(block_size)}m"  
        

        # delete the generate file at the end
        if self.keep_files:
            ior_command += f" -k"
        ior_command += f" -O summaryFile={self.summary_file}" # Path where the output will be written 
        ior_command += f" -O summaryFormat=default"
        # Path where the output will be read
        ior_command += f" -o {self.input_file}"
        
        return ior_command

class ReadIORRandom(TestIOR):
    '''
    I/O pattern: random read in a single shared file.
    '''

    def __init__(self, config: 'IOPSConfig', round_path: Path, test_parameters: dict):
        super().__init__(config, round_path, test_parameters)
        self.input_file = None
    
    def set_input_file(self, input_file: Path) -> None:
        """
        Set the input file for the read operation.
        
        :param input_file: The path to the input file to be read.
        """
        self.input_file = input_file
        if not self.config.mode == ExecutionMode.DEBUG and not self.input_file.exists():
            raise ValueError(f"Input file {self.input_file} does not exist. Please set a valid input file.")

    def get_command(self) -> str:
        """
        Generate the IOR command based on the parameters defined in TestIOR.
        """        
        if self.input_file is None:
            raise ValueError("Input file not set. Please set the input file before generating the command.")
        
        ior_command : str = "ior"

        block_size : int = self.volume / (self.config.processes_per_node * self.computing)
       
        # Add parameters to the command

        ior_command += f" -r" 
        ior_command += f" -t 1m"  
        ior_command += f" -b {int(block_size)}m"  
        

        # delete the generate file at the end
        if self.keep_files:
            ior_command += f" -k"
        ior_command += f" -z"
        ior_command += f" --random-offset-seed={randint(1, 1000)}" # random seed
        ior_command += f" -O summaryFile={self.summary_file}"
        ior_command += f" -O summaryFormat=default"
        # Path where the output will be read
        ior_command += f" -o {self.input_file}"
        return ior_command